name: PHP Composer

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --no-check-all
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
  
    - name: Set GITHUB_TOKEN
      run: composer config --global github-oauth.github.com ${{ secrets.ACCESS_TOKEN }}

    - name: Create Project
      run: composer create-project moodle/moodle .

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Compress Archive
      run: composer archive --file=moodle45 --format=zip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Sync to S3
    # run: aws s3 sync ./vendor/moodle/moodle/moodle45.zip s3://moodle-artifact-bucket
      run: aws s3 sync . s3://moodle-artifact-bucket

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
